theme: jekyll-theme-cayman
title: Hands on advanced machine learning for information extraction from tweets tasks, data, and open source tools
github:
  project_title: Hands on advanced machine learning for information extraction from tweets tasks, data, and open source tools
  project_tagline: To be presented at ACM HYPERTEXT 2019
google_analytics: UA-44393164-1  
